// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:certifide_inspektor/data/inspection_storage_model.dart';
import 'package:certifide_inspektor/models/local_inspection.dart';
import 'package:certifide_inspektor/models/pending_image.dart';
import 'package:certifide_inspektor/models/pending_media.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(InspectionStorageModelAdapter());
    registerAdapter(LocalInspectionAdapter());
    registerAdapter(PendingImageAdapter());
    registerAdapter(PendingMediaAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(InspectionStorageModelAdapter());
    registerAdapter(LocalInspectionAdapter());
    registerAdapter(PendingImageAdapter());
    registerAdapter(PendingMediaAdapter());
  }
}
